version: 2

jobs:
  build1:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: |
            env
            echo "hello there"

  build2:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: |
            echo "raining again?"

workflows:
  version: 2
  build1_and_build2:
    jobs:
      - build1
      - build2:
          requires:
            - build1
